# Assignment 2
For this assignment you'll be looking at 2017 data on immunizations from the CDC. Your datafile for this assignment is in [assets/NISPUF17.csv](assets/NISPUF17.csv). A data users guide for this, which you'll need to map the variables in the data to the questions being asked, is available at [assets/NIS-PUF17-DUG.pdf](assets/NIS-PUF17-DUG.pdf). **Note: you may have to go to your Jupyter tree (click on the Coursera image) and navigate to the assignment 2 assets folder to see this PDF file).**

In [9]:
#mine
import pandas as pd
import numpy as np
df = pd.read_csv("assets/NISPUF17.csv")
df.head()

Unnamed: 0  SEQNUMC  SEQNUMHH  PDAT    PROVWT_D     RDDWT_D  STRATUM  YEAR  \
0           1   128521     12852     2         NaN  235.916956     1031  2017   
1           2    10741      1074     2         NaN  957.353840     1068  2017   
2           3   220011     22001     2         NaN  189.611299     1050  2017   
3           4    86131      8613     1  675.430817  333.447418     1040  2017   
4           5   227141     22714     1  482.617748  278.768063     1008  2017   

   AGECPOXR  HAD_CPOX  ...  XVRCTY2  XVRCTY3  XVRCTY4  XVRCTY5  XVRCTY6  \
0       NaN         2  ...                        NaN      NaN      NaN   
1       NaN         2  ...                        NaN      NaN      NaN   
2       NaN         2  ...                        NaN      NaN      NaN   
3       NaN         2  ...                        NaN      NaN      NaN   
4       NaN         2  ...                        NaN      NaN      NaN   

   XVRCTY7  XVRCTY8  XVRCTY9  INS_STAT2_I  INS_BREAK_I  
0      NaN      NaN      NaN          NaN          NaN  
1      NaN      NaN      NaN          NaN          NaN  
2      NaN      NaN      NaN          NaN          NaN  
3      NaN      NaN      NaN          1.0          2.0  
4      NaN      NaN      NaN          2.0          1.0  

[5 rows x 454 columns]

In [10]:
df.describe()

Unnamed: 0        SEQNUMC      SEQNUMHH          PDAT      PROVWT_D  \
count  28465.000000   28465.000000  28465.000000  28465.000000  15333.000000   
mean   14233.000000  136341.024697  13633.998033      1.461338    376.816991   
std     8217.282043   78822.308954   7882.230931      0.498512    646.828310   
min        1.000000      11.000000      1.000000      1.000000      3.174044   
25%     7117.000000   68071.000000   6807.000000      1.000000     76.216327   
50%    14233.000000  136421.000000  13642.000000      1.000000    195.015630   
75%    21349.000000  204521.000000  20452.000000      2.000000    456.216316   
max    28465.000000  272671.000000  27267.000000      2.000000  11555.055610   

            RDDWT_D       STRATUM     YEAR    AGECPOXR      HAD_CPOX  ...  \
count  28465.000000  28465.000000  28465.0  390.000000  28465.000000  ...   
mean     202.976811   1960.210891   2017.0    2.448718      2.272756  ...   
std      326.449265    271.004165      0.0    1.090358      4.656318  ...   
min        2.895375   1001.000000   2017.0    1.000000      1.000000  ...   
25%       44.494731   2013.000000   2017.0    2.000000      2.000000  ...   
50%      113.260066   2034.000000   2017.0    2.000000      2.000000  ...   
75%      250.143911   2057.000000   2017.0    3.000000      2.000000  ...   
max     6240.054554   2108.000000   2017.0    4.000000     99.000000  ...   

       XROTTY8  XROTTY9  XVRCTY4  XVRCTY5  XVRCTY6  XVRCTY7  XVRCTY8  XVRCTY9  \
count      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
mean       NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
std        NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
min        NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
25%        NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
50%        NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
75%        NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
max        NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN   

        INS_STAT2_I   INS_BREAK_I  
count  15333.000000  15307.000000  
mean       1.632949      1.969230  
std        0.760621      0.350329  
min        1.000000      1.000000  
25%        1.000000      2.000000  
50%        1.000000      2.000000  
75%        2.000000      2.000000  
max        4.000000      4.000000  

[8 rows x 414 columns]

In [11]:
df.shape

(28465, 454)

In [12]:
df['EDUC1'].describe()

count    28465.000000
mean         3.103355
std          1.024468
min          1.000000
25%          2.000000
50%          3.000000
75%          4.000000
max          4.000000
Name: EDUC1, dtype: float64

In [13]:
edc = df['EDUC1']
n = len(edc)
12 in edc.values

False

In [14]:
#method1
q1=np.sum(edc==1) / n
q2=np.sum(edc==2) / n
q3=np.sum(edc==3) / n
q4=np.sum(edc==4) / n
{"less than high school":q1,
"high school":q2,
"more than high school but not college":q3,
"college":q4}


{'less than high school': 0.10202002459160373,
 'high school': 0.172352011241876,
 'more than high school but not college': 0.24588090637625154,
 'college': 0.47974705779026877}

In [16]:
perc = edc.value_counts(normalize=True, sort=False, bins=[0,1,2,3,4])
#format = lambda x: round(x,2)
#perc.apply(format)
#p = perc.apply(format)
p = perc.values
print(p)
print(sum(p))

[0.10202002 0.17235201 0.24588091 0.47974706]
1.0


In [17]:
#method2
dit= {"less than high school":p[0],
    "high school":p[1],
    "more than high school but not college":p[2],
    "college":p[3]}
dit

{'less than high school': 0.10202002459160373,
 'high school': 0.172352011241876,
 'more than high school but not college': 0.24588090637625154,
 'college': 0.47974705779026877}

In [18]:
dit['less than high school']

0.10202002459160373

In [21]:
perc2 = edc.value_counts(normalize=False, sort=False, bins=[0,1,2,3,4])
#format = lambda x: round(x,2)
#perc.apply(format)
#p = perc.apply(format)
p = perc2.values
print(p)
print(sum(p))

[ 2904  4906  6999 13656]
28465


## Question 1
Write a function called `proportion_of_education` which returns the proportion of children in the dataset who had a mother with the education levels equal to less than high school (<12), high school (12), more than high school but not a college graduate (>12) and college degree.

*This function should return a dictionary in the form of (use the correct numbers, do not round numbers):* 
```
    {"less than high school":0.2,
    "high school":0.4,
    "more than high school but not college":0.2,
    "college":0.2}
```


In [19]:
def proportion_of_education():
    # your code goes here
    # YOUR CODE HERE
    ##create quantiles (percents) based on 5 categories
    ##Normalize=True presents as percents, not counts
    perc = edc.value_counts(normalize=True, sort=False, bins=[0,1,2,3,4])
    p = perc.values
    dic = {"less than high school":p[0],
    "high school":p[1],
    "more than high school but not college":p[2],
    "college":p[3]}
    return dic
    raise NotImplementedError()

In [20]:
assert type(proportion_of_education())==type({}), "You must return a dictionary."
assert len(proportion_of_education()) == 4, "You have not returned a dictionary with four items in it."
assert "less than high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "more than high school but not college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."


In [228]:
bf = sum(df['CBF_01']==1)
print(bf)
nbf = bf = sum(df['CBF_01']==2)
nbf

24261


4085

In [229]:
df['P_NUMFLU']

0        NaN
1        NaN
2        NaN
3        3.0
4        0.0
        ... 
28460    NaN
28461    NaN
28462    NaN
28463    NaN
28464    NaN
Name: P_NUMFLU, Length: 28465, dtype: float64

In [230]:
dff = df[df['P_NUMFLU'].notna()]

In [231]:
bf = sum(dff['CBF_01']==1)
print(bf)
nbf = bf = sum(dff['CBF_01']==2)
nbf

13291


1997

In [232]:
n1 = dff[dff['CBF_01'] == 1]['P_NUMFLU']
n2 = dff[dff['CBF_01'] == 2]['P_NUMFLU']

In [233]:
n1.mean(),n2.mean()

(1.8799187420058687, 1.5963945918878317)

## Question 2

Let's explore the relationship between being fed breastmilk as a child and getting a seasonal influenza vaccine from a healthcare provider. Return a tuple of the average number of influenza vaccines for those children we know received breastmilk as a child and those who know did not.

*This function should return a tuple in the form (use the correct numbers:*
```
(2.5, 0.1)
```

In [234]:
def average_influenza_doses():
    # YOUR CODE HERE
    dff = df[df['P_NUMFLU'].notna()]
    n1 = dff[dff['CBF_01'] == 1]['P_NUMFLU']
    n2 = dff[dff['CBF_01'] == 2]['P_NUMFLU']
    return(n1.mean(),n2.mean())
    raise NotImplementedError()

In [235]:
assert len(average_influenza_doses())==2, "Return two values in a tuple, the first for yes and the second for no."


In [236]:
np.sum(df['HAD_CPOX'].isna())

0

In [237]:
df.shape

(28465, 454)

In [238]:

# YOUR CODE HERE
dff = df.copy()
dff['HAD_CPOX'].replace([77,99],[None,None],inplace=True)
#dff['P_NUMVRC'].replace(np.nan,None,inplace=True)
dfn = dff[dff['HAD_CPOX'].notna()]
dfnn = dfn[dfn['P_NUMVRC'].notna()]
A = dfnn[dfnn['P_NUMVRC'] > 0]
M = A[A['SEX'] == 1]
F = A[A['SEX'] == 2]
m1 = M[M['HAD_CPOX'] == 1]
m2 = M[M['HAD_CPOX'] == 2]
f1 = F[F['HAD_CPOX'] == 1]
f2 = F[F['HAD_CPOX'] == 2]
sum1 = m1.shape[0] / m2.shape[0]
sum2 = f1.shape[0] / f2.shape[0]
#sum1 = len(f1['HAD_CPOX'])/len(f2['HAD_CPOX'])
#sum2 = len(m1['HAD_CPOX'])/len(m2['HAD_CPOX'])
dicc = {"male":sum1,
    "female":sum2}


In [239]:
dicc

{'male': 0.009675583380762664, 'female': 0.0077918259335489565}

In [240]:
M['SEX']

10       1
12       1
16       1
19       1
21       1
        ..
28435    1
28436    1
28438    1
28447    1
28449    1
Name: SEX, Length: 7096, dtype: int64

In [241]:
np.sum(dfnn['P_NUMVRC'].isna())

0

In [242]:
dicc

{'male': 0.009675583380762664, 'female': 0.0077918259335489565}

In [243]:
np.sum(dfnn['P_NUMVRC'].isnull())

0

In [244]:
np.sum(dfnn['HAD_CPOX'].isnull())

0

In [245]:
dfnn['P_NUMVRC'].unique()

array([1., 0., 2., 3.])

In [246]:
dfnn['HAD_CPOX'].unique()

array([2., 1.])

In [247]:
dff.shape

(28465, 454)

In [248]:
dfn.shape

(28357, 454)

In [249]:
dfnn.shape

(15286, 454)

In [250]:
dfn.shape

(28357, 454)

In [251]:
g = dff[dff['HAD_CPOX'].notna()]
len(g['HAD_CPOX'])

28357

In [252]:
len(dfn['HAD_CPOX'])

28357

In [253]:
dfn['HAD_CPOX'].unique()

array([2., 1.])

In [254]:
type(dicc['female'])

float

In [255]:
dicc = {"male":0.2,
    "female":0.4}

-1 <= dicc['female'] <= 1

True

## Question 3
It would be interesting to see if there is any evidence of a link between vaccine effectiveness and sex of the child. Calculate the ratio of the number of children who contracted chickenpox but were vaccinated against it (at least one varicella dose) versus those who were vaccinated but did not contract chicken pox. Return results by sex. 

*This function should return a dictionary in the form of (use the correct numbers):* 
```
    {"male":0.2,
    "female":0.4}
```

Note: To aid in verification, the `chickenpox_by_sex()['female']` value the autograder is looking for starts with the digits `0.0077`.

In [257]:
def chickenpox_by_sex():
    # YOUR CODE HERE
    dff = df.copy()
    dff['HAD_CPOX'].replace([77,99],[None,None],inplace=True)
    #dff['P_NUMVRC'].replace(np.nan,None,inplace=True)
    ##Remove na & nan values from DataFrame with by considering HAD_CPOX and P_NUMVRC column respectively
    dfn = dff[dff['HAD_CPOX'].notna()]
    dfnn = dfn[dfn['P_NUMVRC'].notna()]
    ## determined children that are vaccinated against chicken-pox (at least 1 varicella dose):
    A = dfnn[dfnn['P_NUMVRC'] > 0]
    ## separate vaccinated children by sex
    M = A[A['SEX'] == 1]
    F = A[A['SEX'] == 2]
    ## separate males that have contracted chicken_pox and those that did not
    m1 = M[M['HAD_CPOX'] == 1]
    m2 = M[M['HAD_CPOX'] == 2]
    ## separate females that have contracted chicken_pox and those that did not
    f1 = F[F['HAD_CPOX'] == 1]
    f2 = F[F['HAD_CPOX'] == 2]
    ## calculate the ratio of males that contracted chicken_pox vs those that did not (do the same for female)
    sum1 = m1.shape[0] / m2.shape[0]
    sum2 = f1.shape[0] / f2.shape[0]
    #sum1 = len(f1['HAD_CPOX'])/len(f2['HAD_CPOX'])
    #sum2 = len(m1['HAD_CPOX'])/len(m2['HAD_CPOX'])
    dicc = {"male":sum1,
        "female":sum2}
    return dicc
    raise NotImplementedError()

In [258]:
assert len(chickenpox_by_sex())==2, "Return a dictionary with two items, the first for males and the second for females."


In [259]:
chickenpox_by_sex()

{'male': 0.009675583380762664, 'female': 0.0077918259335489565}

In [260]:

import scipy.stats as stats
import numpy as np
import pandas as pd

# YOUR CODE HERE
dff = df.copy()
dff['HAD_CPOX'].replace([77,99],[None,None],inplace=True)
#dff['P_NUMVRC'].replace(np.nan,None,inplace=True)
dff = dff[dff['HAD_CPOX'].notna()]
dff = dff[dff['P_NUMVRC'].notna()]
dft['had_chickenpox_column'] = dff['HAD_CPOX']
dft['num_chickenpox_vaccine_column'] = dff['P_NUMVRC']   

# this is just an example dataframe
dft=pd.DataFrame({"had_chickenpox_column":np.random.randint(1,3,size=(100)),
               "num_chickenpox_vaccine_column":np.random.randint(0,6,size=(100))})

# here is some stub code to actually run the correlation
corr, pval=stats.pearsonr(dft["had_chickenpox_column"],dft["num_chickenpox_vaccine_column"])

# just return the correlation
#return corr

                                
                                

In [261]:
corr

-0.038018431040293454

In [262]:
pval

0.7072587028714442

## Question 4
A correlation is a statistical relationship between two variables. If we wanted to know if vaccines work, we might look at the correlation between the use of the vaccine and whether it results in prevention of the infection or disease [1]. In this question, you are to see if there is a correlation between having had the chicken pox and the number of chickenpox vaccine doses given (varicella).

Some notes on interpreting the answer. The `had_chickenpox_column` is either `1` (for yes) or `2` (for no), and the `num_chickenpox_vaccine_column` is the number of doses a child has been given of the varicella vaccine. A positive correlation (e.g., `corr > 0`) means that an increase in `had_chickenpox_column` (which means more no’s) would also increase the values of `num_chickenpox_vaccine_column` (which means more doses of vaccine). If there is a negative correlation (e.g., `corr < 0`), it indicates that having had chickenpox is related to an increase in the number of vaccine doses.

Also, `pval` is the probability that we observe a correlation between `had_chickenpox_column` and `num_chickenpox_vaccine_column` which is greater than or equal to a particular value occurred by chance. A small `pval` means that the observed correlation is highly unlikely to occur by chance. In this case, `pval` should be very small (will end in `e-18` indicating a very small number).

[1] This isn’t really the full picture, since we are not looking at when the dose was given. It’s possible that children had chickenpox and then their parents went to get them the vaccine. Does this dataset have the data we would need to investigate the timing of the dose?

In [263]:
def corr_chickenpox():
    import scipy.stats as stats
    import numpy as np
    import pandas as pd
    
    # YOUR CODE HERE
    dff = df.copy()
    dff['HAD_CPOX'].replace([77,99],[None,None],inplace=True)
    #dff['P_NUMVRC'].replace(np.nan,None,inplace=True)
    dff = dff[dff['HAD_CPOX'].notna()]
    dff = dff[dff['P_NUMVRC'].notna()]
    # this is just an example dataframe
    dft=pd.DataFrame({"had_chickenpox_column":dff['HAD_CPOX'],
                   "num_chickenpox_vaccine_column":dff['P_NUMVRC']})
    # here is some stub code to actually run the correlation
    corr, pval=stats.pearsonr(dft["had_chickenpox_column"],dft["num_chickenpox_vaccine_column"])
    # just return the correlation
    #return corr
    return corr
    raise NotImplementedError()

In [264]:
assert -1<=corr_chickenpox()<=1, "You must return a float number between -1.0 and 1.0."
